baseURL = "https://blackness.me/"
languageCode = "tr-tr"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Show reading time in minutes for posts
  showReadingTime = true

[languages]
  [languages.en]
    title = "Blog."
    keywords = ""
    copyright = ""
    menuMore = "Dahası"
    readMore = "Dahası"
    readOtherPosts = "Başka"
    writtenBy = ""
    newerPosts = "Yenisi"
    olderPosts = "Eskisi"
    minuteReadingTime = "dakikada okursun"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "blackness"
      logoHomeLink = "/"

    [languages.en.menu]
#      [[languages.en.menu.main]]
#        identifier = "about"
#        name = "About"
#        url = "/about"

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
